### PR TITLE
[Dubbo-2499]fix PojoUtil realize type convert not support subclasses of 'java.util.date' #2499

### PR DESCRIPTION
**Pull request by ningyu1**
## What is the purpose of the change

fix PojoUtil realize type convert not support subclasses of 'java.util.date' #2499 

## Brief changelog

The type convert was modified to support the 'java.util.date' subclass

## Verifying this change

org.apache.dubbo.common.utils.CompatibleTypeUtils.java
org.apache.dubbo.common.utils.PojoUtilsTest.java
org.apache.dubbo.common.utils.CompatibleTypeUtilsTest.java

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [x] Run `mvn clean install -DskipTests` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by diecui1202** [comment]
Looks good to me.

**Comment by diecui1202** [comment]
Need to merge back to 2.6.x?

**Comment by ningyu1** [comment]
@diecui1202 Yes ，I will send a pr that fixes the 2.6.x branch.

**Comment by ningyu1** [comment]
merge to 2.6.x #2502

**Pull request merged**
