### PR TITLE
[Dubbo-2838] Fix UT failed on windows with FileNetworkerTest

### PR DESCRIPTION
**Pull request by biyuhao**
## What is the purpose of the change

Fix Dubbo-2838

## Brief changelog

Fix FileNetworkerTest failure

## Verifying this change

Run UT on windows platform

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [x] Run `mvn clean install -DskipTests` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [x] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by biyuhao** [comment]
Fix #2838

**Comment by carryxyh** [comment]
I have seen another pr to fix this issue:
https://github.com/apache/incubator-dubbo/pull/2848

Personally think that his modification is simpler and effective.

What do u think about it?

**Comment by biyuhao** [comment]
Please refer to https://en.wikipedia.org/wiki/File_URI_scheme
Actually an additional slash is only for Windows local file which hostname is omitted.
And for Unix like system remains the same. (`file:///tmp/junit2484075406115019206/junit2016855624112146186.tmp` ,three slashes in total including the root path one)

In fact the UT passed, so I think both pr are fine.  😄

**Comment by carryxyh** [comment]
Hi,
We don't need to judge our system, we just need to add a '/'. The content after the third '/' will be considered the path of the URL (the current way of parsing dubbo). I know that this problem is caused by the separator of WINDOWS. But in the way of fixing, I think we only need to add a '/' to move closer to dubbo's parsing. 

Another thing is that that pr is simpler. So I personally prefer that one.  Thx for your pr, too. Very nice solution. 👍

**Pull request closed without merging**
