### PR TITLE
polish code and fix some documentation errors

### PR DESCRIPTION
**Pull request by kezhenxu94**
## What is the purpose of the change

polish code and fix some documentation errors

## Brief changelog

org.apache.dubbo.registry.etcd.EtcdRegistry

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by LiZhenNet** [comment]
LGTM

**Comment by kezhenxu94** [comment]
> LGTM

Hi @LiZhenNet , it's better to follow the [review guide](https://help.github.com/en/articles/about-pull-request-reviews)   :)

**Comment by ralf0131** [comment]
Hi, I did some changes to this class in #3663, mind wait for some time? Since if this pull request get merged, there might be quite a lot of conflict.

**Comment by kezhenxu94** [comment]
> Hi, I did some changes to this class in #3663, mind wait for some time? Since if this pull request get merged, there might be quite a lot of conflict.

Never mind :)

**Comment by ralf0131** [comment]
Thanks, I just applied a DO-NOT-MERGE label.

**Comment by kezhenxu94** [comment]
Since #3663 is merged, I'll remove DO-NOT-MERGE label for others to review and merge(if possible)

**Comment by LiZhenNet** [comment]
> > LGTM
> 
> Hi @LiZhenNet , it's better to follow the [review guide](https://help.github.com/en/articles/about-pull-request-reviews) :)

This PR is only fixed the syntax for comments and used diamond-operator,
It look good to me ,I have no comment about it.

**Pull request merged**
