### PR TITLE
#2134 Fix dependency conflict issue for com.alibaba:dubbo-rpc-thrift

### PR DESCRIPTION
**Pull request by LeoAugust19**
https://github.com/apache/incubator-dubbo/issues/2134

### CODE REVIEW

**Comment by LeoAugust19** [comment]
@kimmking PR to solve #2134. Thanks a lot.

**Comment by diecui1202** [comment]
@LeoAugust19 Could you solve the conflict?

**Comment by LeoAugust19** [comment]
@diecui1202 Yes! This patch can solve the conflict problem.

**Comment by diecui1202** [comment]
@LeoAugust19 I mean the conflict of the git merge.

image

**Comment by LeoAugust19** [comment]
https://github.com/LeoAugust19/incubator-dubbo/commit/6d76c5f2dafa5782a0eaf9919e883d0c0357cfba

**Comment by LeoAugust19** [comment]
@diecui1202 The conflict problem is solved by this patch.

**Comment by diecui1202** [comment]
@LeoAugust19 I suggest you create a new branch from apache/incubator-dubbo:master, then merge your branch to the new branch. then start a new PR.

**Comment by diecui1202** [comment]
image


I don't know what happened to this PR. I suggest close it first and start a new PR if necessary.

**Comment by diecui1202** [comment]
@LeoAugust19

**Pull request closed without merging**
