### PR TITLE
Add Erlang Implementation

### PR DESCRIPTION
**Pull request by DLive**
Add Erlang language impementation  repository url.

### CODE REVIEW

**Comment by DLive** [comment]
> I think [dubboerl](https://github.com/dubboerl/dubboerl) needs to be improved, at least readme needs to be improved.

I made some changes to readme. 
For the other features of the project we will continue to improve.

**Comment by ralf0131** [comment]
Hi, nice work!

I think this is something worth notifying the dev@dubbo.apache.org mailing list. Could you send an email first?
Another question, would you consider transfer it to Apache Dubbo, or transfer to github.com/dubbo group?

**Comment by DLive** [comment]
> Hi, nice work!
> 
> I think this is something worth notifying the [dev@dubbo.apache.org](mailto:dev@dubbo.apache.org) mailing list. Could you send an email first?
> Another question, would you consider transfer it to Apache Dubbo, or transfer to github.com/dubbo group?
I will send a mail later.
I'm happy to be transfer. What can I do about this work.

**Comment by DLive** [comment]
> Hi, nice work!
> 
> I think this is something worth notifying the [dev@dubbo.apache.org](mailto:dev@dubbo.apache.org) mailing list. Could you send an email first?
> Another question, would you consider transfer it to Apache Dubbo, or transfer to github.com/dubbo group?

I will send a mail later.
I'm happy to be transfer. What can I do about this work.

**Pull request merged**
