### PR TITLE
[BUGFIX]Fix/issue 2006

### PR DESCRIPTION
**Pull request by fingthinking**
## What is the purpose of the change

fix: [https://github.com/apache/incubator-dubbo/issues/2006](https://github.com/apache/incubator-dubbo/issues/2006)

## Brief changelog

当有异常发生在 `ExchangeCode` 的 `encodeResponse` 方法的时候，会发送一个`exception response`给 consume，但是初始的 response 也会在`exception response` 被发送完成之后给发送出去，就会出现发送两次的情况，导致服务出现异常
When an exception occurs in the encodeResponse method of `ExchangeCode`, an `exception response` is sent to consume, but the initial response is also sent out after the `exception response` is sent out, which causes an exception to the service.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by diecui1202** [comment]
@fingthinking could u pls add some UT for this scenario?

**Comment by beiwei30** [comment]
@fingthinking I happened to visit your change today. Would you mind to explain why 'buffer.clear()' is necessary? I think `buffer.writerIndex(savedWriteIndex)` should work.

**Comment by fingthinking** [comment]
@beiwei30 抱歉哈，我的错，看的是历史的 dubbox 代码，没有这部分逻辑。

**Comment by beiwei30** [comment]
thanks 👍

**Comment by zhaogaiwen** [comment]
@fingthinking 大佬，我没太看懂是怎么解决这个问题的，可以详细点吗？

**Pull request closed without merging**
