### PR TITLE
Hessian support attachments and add log4j2 support.

### PR DESCRIPTION
**Pull request by sc834466168**
1、修复hessian 重载方法时报错问题
[http://blog.csdn.net/sanfye/article/details/49390493](url)

2、添加log4j2的支持
与原log2j配置一致
添加配置dubbo.log4j.console, 是否添加输出至控制台

3、修复hessian 隐形参数失效问题
RpcContext中的getAttachments无法获取到消费者端传来的参数
a) 未设置attachments参数
b)debug过程中发现被InvokerInvocationHandler类重置

暂时想到的办法是在httpclient中添加header进行传输, 由于上述b重试了 RpcInvocation类, ContextFilter无法获取到attachments, 临时解决方案是HessianProtocol类中设置ThreadLocal保证线程安全, 在使用HessianFilter进行参数设置

### CODE REVIEW

**Comment by chickenlj** [comment]
Would you please separate this two features? We prefer to have each PR focus on solution for a single 
problem.

**Comment by ralf0131** [comment]
> Would you please separate this two features? We prefer to have each PR focus on solution for a single problem.

+1 It is too complicated to review this pull request, please keep it simple.

**Comment by diecui1202** [comment]
I am considering about this. https://github.com/apache/incubator-dubbo/pull/1801

On the provider side, a HessianFilter is not a good way. I will try to restore context in HessianHandler.

**Comment by diecui1202** [comment]
@sc834466168 IMO, you could submit a new PR for supporting log4j2.

**Comment by chickenlj** [comment]
Hessian attachments has been supported with #1801.
Would you please file a new PR for log4j2 support? I will close this one anyway.

**Pull request closed without merging**
