### PR TITLE
fix issue #195: @Reference check=false不生效

### PR DESCRIPTION
**Pull request by beiwei30**
## What is the purpose of the change

fix issue #195: @Reference check=false不生效

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by liunancun** [comment]
这次修改是不是有问题啊，把org.apache.dubbo.config.AbstractServiceConfig.dynamic默认值改成false了，导致注册到zk的服务都变成了静态服务？

**Comment by liunancun** [comment]
@beiwei30 @lixiaojiee

**Comment by dhchao11** [comment]
> 这次修改是不是有问题啊，把org.apache.dubbo.config.AbstractServiceConfig.dynamic默认值改成false了，导致注册到zk的服务都变成了静态服务？

我也发现这个问题了

**Comment by dhchao11** [comment]
可以解释下，为什么AbstractServiceConfig中的dynamic加了false默认值吗

**Comment by CrazyHZM** [comment]
> 可以解释下，为什么AbstractServiceConfig中的dynamic加了false默认值吗

已经改回来了

**Comment by dhchao11** [comment]
> > 可以解释下，为什么AbstractServiceConfig中的dynamic加了false默认值吗
> 
> 已经改回来了

是的是的，我也刚看到。

**Comment by 9526xu** [comment]
使用 2.7.1 踩到这个坑了😢

**Pull request merged**
