### PR TITLE
fix a bug of service config

### PR DESCRIPTION
**Pull request by tswstarplanet**
## What is the purpose of the change

fix a bug of service config that the change of protocol config 'register' cannot work on the config of dubbo service if the user does not config 'register' of dubbo service

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by tswstarplanet** [comment]
这个提交出于以下目的，ServiceConfig会先加载ProtocolConfig的配置，之后加载自身的配置。如果两者有相同的配置项的话，ServiceConfig的配置会覆盖ProtocolConfig的配置。但之前的这个条件判断，是在加载了ProtocolConfig以及ServiceConfig之后，又修改了ProtocolConfig的值。这应该是不合理的，因为单独改变ProtocolConfig的配置没什么意义。所以应该放到前面。
而map中的notify属性，放到前面或者后面应该都没关系。所以就一起放到了前面。

**Comment by beiwei30** [comment]
@tswstarplanet I think we cannot adjust the sequence as you proposed, since we need to make sure local registry will not do registration even if service claims itself should be registered, for example:

```xml
    <dubbo:protocol name="local" port="20890"/>
    <dubbo:service interface="com.acme.DemoService" ref="demoService" register="true"/>
```

**Comment by beiwei30** [comment]
@tswstarplanet I discussed with other dubbo folks, and we believe the code you adjusted are in fact useless code. Would you mind to remove them instead of adjust its location?

Thanks.

**Comment by tswstarplanet** [comment]
OK

**Comment by tswstarplanet** [comment]
@beiwei30 I have removed the piece of code

**Pull request merged**
