### PR TITLE
Lazy export will start multi server / Making all export/refer process serial. 

### PR DESCRIPTION
**Pull request by bohrqiu**
## What is the purpose of the change

fix some dubbo bug

## Brief changelog

1. lazy export will start multi server
2. tuning spring event performance
3. clean FailbackRegistry resouces

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/alibaba/dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by chickenlj** [comment]
> tuning spring event performance
I've fixed this with commit 89b4771d0a91ddb2b895b84ea7875d88968668bc

> lazy export will start multi server
We're considering solve this by turning all export/refer process serial.
also see this issue #677

**Comment by chickenlj** [comment]
> clean FailbackRegistry resouces

The thread here is daemon, and this is not a critical operation that have to wait.

**Comment by bohrqiu** [comment]
We're considering solve this by turning all export/refer process serial.

why do this？

when there are hundreds of providers/consumer，the startup performance will be slow.

in our internal version:



wechatimg117

**Comment by bohrqiu** [comment]
in our internal version,i have enhance dubbo includes the following：

1. hessian data compress for across datacenter invokes.

image


2. export/refer concurrent

3. dubbo local cache .

  dubbo consumer invoke redis first,when cache missing,invoke remote serivce. it use `spring el` compute key.


wechatimg118

**Comment by chickenlj** [comment]
Your project cost more than 147s to finish start? Is there any time costing initialization process in your service bean? 
Is the cost mainly on the consumer side, waiting for the registry notification of providers and establish connection? If so, maybe we can make the notification process(time costing) asynchronous.

**Comment by chickenlj** [comment]
> dubbo local cache .

You used dubbo's `Cache` SPI to achieve this?

**Comment by bohrqiu** [comment]
Is the cost mainly on the consumer side, waiting for the registry notification of providers and establish connection? If so, maybe we can make the notification process(time costing) asynchronous.

yes,when consumer side refer service,it will establish connection and access registry center,it be better async refer

**Comment by bohrqiu** [comment]
You used dubbo's Cache SPI to achieve this?

it use filter,spring el+redis .

**Comment by ralf0131** [comment]
Please resolve the conflicts.

**Comment by beiwei30** [comment]
@bohrqiu I checked all your changes, and found the similar changes have been made for ServiceBean and FailbackRegistry, and because there's conflict, I manually submit your change made against DubboProtocol, see https://github.com/apache/incubator-dubbo/pull/1916.

**Comment by beiwei30** [comment]
@bohrqiu for other enhancements you mentioned on this PR, would you mind to submit more PRs?

**Comment by bohrqiu** [comment]
@beiwei30 , I will open new PRs, close this PR ,thanks

**Comment by beiwei30** [comment]
looking forward to

**Pull request closed without merging**
