### PR TITLE
Ensure compatibility for elegant shutdown under servlet container. #1998

### PR DESCRIPTION
**Pull request by ralf0131**
## What is the purpose of the change

Ensure compatibility for elegant shutdown under servlet container. #1998

## Brief changelog

Consider the following cases: 

1. listener class ContextLoaderListener is defined in web.xml.
  servlet container will initialized ContextLoaderListener before this class. Therefore Dubbo's elegant shutdown feature will not be enabled. To enable it, you need to either: 1) remove listener class ContextLoaderListener in your web.xml 2) change listener class to DubboContextLoaderListener in your web.xml 

2. listener class DubboContextLoaderListener is defined in web.xml This is automatically enable Dubbo's elegant shutdown feature, even for a servlet container which is not 3.0 compatible 

3. no listener class defined in web.xml Dubbo's elegant shutdown feature will be automatically enabled if Dubbo is running under a servlet 3.0+ compatible container see DubboWebApplicationInitializer for more details.

## Verifying this change

Run and test the above 3 cases.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [x] Run `mvn clean install -DskipTests` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by chickenlj** [comment]
In a pure Spring (non-web) case, do we need to register `context.addApplicationListener(new DubboApplicationListener());` mannually?

The configuration various with different use cases, so we'd better provide docs or blogs of how to use covering all use cases.

**Comment by ralf0131** [comment]
> In a pure Spring (non-web) case, do we need to register context.addApplicationListener(new DubboApplicationListener()); mannually?

If we use spring-container provided by Dubbo, it will be there out of the box.
If we use dubbo spring boot starter, it will be there out of the box.
If we use pure spring(non-web),  user will need to add that listener manually.

> The configuration various with different use cases, so we'd better provide docs or blogs of how to use covering all use cases.

Yes, I am planning to add documentation for that.

**Comment by mercyblitz** [comment]
I do not recommend this implementation , and suggest:
* To implement `WebApplicationInitializer` 
* To append `ServletContext`'s parameter for `ApplicationContextInitializer`, whose name is either `ContextLoader.GLOBAL_INITIALIZER_CLASSES_PARAM` or `CONTEXT_INITIALIZER_CLASSES_PARAM` , and its value is your `ApplicationContextInitializer` class.
* To add `DubboApplicationListener` into `ConfigurableApplicationContext` in `ApplicationContextInitializer#initialize` method.

Current approach must be based on Servlet 3.0 + container.

**Comment by ralf0131** [comment]
@mercyblitz I think your suggestion is more elegant. I have changed my implementation based on your idea.

I use web-fragment.xml to ensure the compatibility. The following content:

```xml
    <context-param>
        <param-name>contextInitializerClasses</param-name>
        <param-value>org.apache.dubbo.config.spring.initializer.DubboApplicationContextInitializer</param-value>
    </context-param>

    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>
```

will be merged with user's web.xml whether user has specified ContextLoaderListener or not.

Be aware that the current implementation will only works under a servlet 3.0+ container.

If running on a servlet container that is less than 3.0, user should add the above configuration into web.xml.

**Comment by kexianjun** [comment]
dubbo-config/dubbo-config-spring/src/main/resources/META-INF/web-fragment.xml,This file may have introduced a bug,when running dubbo application in a servlet container,it may load tow ContextLoaderListeners,see #2538 and #2535

**Pull request merged**
