### PR TITLE
a more elegant way

### PR DESCRIPTION
**Pull request by CalvinKirs**
## What is the purpose of the change

a more elegant way，higher efficiency。

## Brief changelog

no

## Verifying this change

yes

Follow this checklist to help us incorporate your contribution quickly and easily:

run the test case

### CODE REVIEW

**Comment by carryxyh** [comment]
Can u give some benchmark to verify that your way is better performance?

**Comment by CalvinKirs** [comment]
> Can u give some benchmark to verify that your way is better performance?

我做过一些测试，从一到百万，用该种方式的效率是原来方式的几十倍

**Comment by CalvinKirs** [comment]
From hashmap

**Comment by carryxyh** [comment]
Attach your code will be better.
Maybe a little ut in org.apache.dubbo.common.timer.HashedWheelTimerTest is enough.

**Comment by CalvinKirs** [comment]
static final int newNormalizeTicksPerWheel(int ticksPerWheel) {
        int n = ticksPerWheel;
        n |= n >>> 1;
        n |= n >>> 2;
        n |= n >>> 4;
        n |= n >>> 8;
        n |= n >>> 16;
        return n + 1;
    }

    public static void main(String[] args) {
        Long startTime = System.currentTimeMillis();
        for (int n = 1; n < 10000000; n++) {
            oldNormalizeTicksPerWheel(n);
        }
        Long endTimeOne = System.currentTimeMillis();
        for (int n = 1; n < 10000000; n++) {
            newNormalizeTicksPerWheel(n);
        }
        System.out.println(endTimeOne - startTime);
        System.out.println(System.currentTimeMillis() - endTimeOne);
    }

    private static int oldNormalizeTicksPerWheel(int ticksPerWheel) {
        int normalizedTicksPerWheel = 1;
        while (normalizedTicksPerWheel < ticksPerWheel) {
            normalizedTicksPerWheel <<= 1;
        }
        return normalizedTicksPerWheel;
    }

**Pull request merged**
