### PR TITLE
[Dubbo-#2162]Correct the reference retries default value 0 to 2

### PR DESCRIPTION
**Pull request by tswstarplanet**

### CODE REVIEW

**Comment by ralf0131** [comment]
Hi, please check the CI failure first.

**Comment by diecui1202** [comment]
@tswstarplanet Does this PR need to merge to 2.6.x ?

**Comment by diecui1202** [comment]
#2162

**Comment by tswstarplanet** [comment]
@diecui1202 Sorry, should I determine what branch this commit to be merged ?

**Comment by diecui1202** [comment]
@tswstarplanet This is a bug, so I think it needs to be merged to master and 2.6.x.

You may need to file 2 PRs, one to master, and one to 2.6.x.

**Comment by diecui1202** [comment]
I think we can merge this PR first. And then start a new PR for 2.6.x

**Comment by diecui1202** [comment]
The PR for 2.6.x is #2303

**Pull request merged**
