### PR TITLE
[Release] Sync 2.6.2-SNAPSHOT to master branch

### PR DESCRIPTION
**Pull request by mercyblitz**
## What is the purpose of the change

Sync 2.6.2-SNAPSHOT to master branch

## Brief changelog

Keep master branch with SNAPSHOT version

## Verifying this change

Maven install locally

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by mercyblitz** [comment]
Temporary close

**Comment by ralf0131** [comment]
Can you reopen this pull request? It is available to be merged now since 2.6.2 release branch has been created.

**Comment by ralf0131** [comment]
This pull request can be reopened because your master branch has been sync forcely, so please create a new pull request.

**Comment by mercyblitz** [comment]
@ralf0131  I will re-do

**Pull request closed without merging**
