### PR TITLE
Extracting public code to the parent class

### PR DESCRIPTION
**Pull request by scxwhite**
Extracting public code to the parent class

### CODE REVIEW

**Comment by ralf0131** [comment]
The UT is failing, please make sure your change does not break the UT.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
Running com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistryTest
log4j:WARN No appenders could be found for logger (com.alibaba.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.268 sec <<< FAILURE! - in com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistryTest
testStatusChecker(com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistryTest)  Time elapsed: 1.029 sec  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <ERROR>
     but: was <OK>
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistryTest.testStatusChecker(ZookeeperRegistryTest.java:137)


Results :

Failed tests: 
  ZookeeperRegistryTest.testStatusChecker:137 
Expected: is <ERROR>
     but: was <OK>

Tests run: 8, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by scxwhite** [comment]
This ut was passed in my local area, and I didn't break this ut. Can you do check again?

**Comment by scxwhite** [comment]
This ut was passed in my local area, and I didn't break this ut. Can you do check again?

**Comment by ralf0131** [comment]
@scxwhite Please do not push commit that make non-sense. I can restart the job if you request.

**Comment by scxwhite** [comment]
I am sorry.

**Comment by ralf0131** [comment]
This pull request looks good to me, however I am no in favor of the name `cexecutor` because people might not know what does it mean.

**Pull request merged**
