### PR TITLE
add unit test for remoting module

### PR DESCRIPTION
**Pull request by htynkn**
## What is the purpose of the change

Increase unit test coverage for remoting module

## Brief changelog

+ add test for remoting-netty4 and remoting-grizzly
+ use NetUtils to get free port for `JettyHttpBinderTest` and `TomcatHttpBinderTest`
+ add curator-test library to fix zookeeper test

## Verifying this change
CI pass

### CODE REVIEW

**Comment by nzomkxia** [comment]
all added tests are passed

**Comment by lovepoem** [comment]
@htynkn ，please add apache license header to new java files

**Comment by htynkn** [comment]
@lovepoem Done. Thanks :)

**Comment by lovepoem** [comment]
Look good to me

**Pull request merged**
