### PR TITLE
修改jdk不兼容问题

### PR DESCRIPTION
**Pull request by Leishunyu**
## What is the purpose of the change

修改由于新老版本jdk不兼容问题引起的排序异常
https://github.com/apache/incubator-dubbo/issues/2799
## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues/2799) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by carryxyh** [comment]
@beiwei30 
Would u pls have a look?

**Comment by carryxyh** [comment]
@Leishunyu 
Would u pls add some unit test for you fix?
:)

**Comment by ralf0131** [comment]
Hi, I would suggest a new class called `AbstractRouter` to  wrap the common logic.
I see there are common attributes e.g. url, priority in `ConditionRouter`, `TagRouter`, and `ScriptRouter`, we need a base class for all the common logic.

For example, we can put `getPriority()` to `AbstractRouter`

**Comment by Leishunyu** [comment]
> Hi, I would suggest a new class called `AbstractRouter` to wrap the common logic.
> I see there are common attributes e.g. url, priority in `ConditionRouter`, `TagRouter`, and `ScriptRouter`, we need a base class for all the common logic.
> 
> For example, we can put `getPriority()` to `AbstractRouter`
Hey, your suggestion has been modified. If you have time, you can check it out. UT will also take time to make up.

**Comment by beiwei30** [comment]
one question, to solve this issue, is it as simple as changing all `compareTo(Router o)` implementation to:

```
    @Override
    public int compareTo(Router o) {
        if (!(o instanceof ScriptRouter)) {
            return 0; // from 1 to 0
        }
       ...
```

instead of introducing `Integer getPriority();` on the interface?

**Pull request closed without merging**
