### PR TITLE
Improve LICENSE and NOTICE according to ASF policy.

### PR DESCRIPTION
**Pull request by ralf0131**
## What is the purpose of the change

Improve LICENSE and NOTICE according to ASF policy.

## Brief changelog

Improve LICENSE and NOTICE according to ASF policy.

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by justinmclean** [comment]
Looks good. Although I've not done a detailed check and would need a release tar ball to check. What's the best way to get a source tar bundle i.e. what exactly is going to be released and placed in the ASF release mirror system?

A couple of very minor things.
1. Re "This product bundles and repackages the following code in Google Guava 16.0.1, which is available under a Apache License 2.0" license. For details, see http://apache.org/licenses/LICENSE-2.0.txt." I would point to https://github.com/google/guava/blob/master/COPYING or better still exact version of that file for that release. (The master file could change in future versions)
2. in NOTICE I'd put "Apache Dubbo (incubating)" rather than "Apache Dubbo"
3. I'd put "Copyright 2018" rather than "Copyright 2018-2018"

Both issues are trivial and wouldn't cause me to vote -1 on a release.

**Comment by ralf0131** [comment]
@justinmclean I have updated according to your review comments.

>  What's the best way to get a source tar bundle i.e. what exactly is going to be released and placed in the ASF release mirror system?

After this pull request being merged, @chickenlj will start the release process. 
We can check it again once the release candidate is available.
IMO the release candidate should contain:
* a source package
* a binary package
* a javadoc package
* a maven artifact

**Comment by justinmclean** [comment]
Hi,

> We can check it again once the release candidate is available.
> IMO the release candidate should contain:
> 
> a source package
> a binary package
> a javadoc package
> a maven artifact

At Apache offical releases are source releases. See [1] [2] Maven and convenience binaries are secondary and not offical releases. Note that a binary release may need a different LICENSE and NOTICE file depending on it’s contents. [3]

So a release candidate will contain source code only, you can vote on a convenience binaries or maven artefact at the same time if you want, but it’s the source release that is important.

Thanks,
Justin

1. http://www.apache.org/legal/release-policy.html#what
2. http://www.apache.org/legal/release-policy.html#what-must-every-release-contain
3. http://www.apache.org/dev/licensing-howto.html#binary

**Comment by chickenlj** [comment]
I will merge the LICENSE and NOTICE part in this PR.

**Pull request merged**
