### PR TITLE
[Dubbo-3258] Replace explicit type parameters with diamond operator #3258

### PR DESCRIPTION
**Pull request by ssoydan**
## What is the purpose of the change

Replace all explicit type parameters with diamond operator (supported with Java7+)

## Brief changelog

"Find and replace" old style parameters with diamond operator by the help of a regular expression and some after manual work for specific cases. 

## Verifying this change

No eclipse warnings or SonarQube issues specific to this case exists anymore.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by ssoydan** [comment]
The test below (testAnyHost) runs successfully on local. Travis build job for Java11 is also successful. The error looks like a temporary one. I think if you can rerun the build, it will be successful.
Thanks.

[[1;31mERROR[m] testAnyHost  Time elapsed: 0.18 s  <<< ERROR!
redis.embedded.exceptions.EmbeddedRedisException: Failed to start Redis instance
	at org.apache.dubbo.registry.redis.RedisRegistryTest.setUp(RedisRegistryTest.java:50)
Caused by: java.io.IOException: Cannot run program "/tmp/1548765836895-0/redis-server-2.8.19" (in directory "/tmp/1548765836895-0"): error=26, Text file busy
	at org.apache.dubbo.registry.redis.RedisRegistryTest.setUp(RedisRegistryTest.java:50)
Caused by: java.io.IOException: error=26, Text file busy
	at org.apache.dubbo.registry.redis.RedisRegistryTest.setUp(RedisRegistryTest.java:50)

**Comment by beiwei30** [comment]
we cannot accept such big pull request. it is very easy to introduce regression. pls. consider to submit this kind of pull request one module after another. 

@ssoydan you could work with @CrazyHZM together. 

In order to collaborate joint efforts better, I created https://github.com/apache/incubator-dubbo/projects/5, feel free to fire new issues and move them in, so that others know what you are working on.

Thanks,
-Ian.

**Comment by CrazyHZM** [comment]
> we cannot accept such big pull request. it is very easy to introduce regression. pls. consider to submit this kind of pull request one module after another.
> 
> @ssoydan you could work with @CrazyHZM together.
> 
> In order to collaborate joint efforts better, I created https://github.com/apache/incubator-dubbo/projects/5, feel free to fire new issues and move them in, so that others know what you are working on.
> 
> Thanks,
> -Ian.

I am willing.

**Comment by beiwei30** [comment]
> > we cannot accept such big pull request. it is very easy to introduce regression. pls. consider to submit this kind of pull request one module after another.
> > @ssoydan you could work with @CrazyHZM together.
> > In order to collaborate joint efforts better, I created https://github.com/apache/incubator-dubbo/projects/5, feel free to fire new issues and move them in, so that others know what you are working on.
> > Thanks,
> > -Ian.
> 
> I am willing.

Folks, pls. fire an issue to let all know which module you are working on, and move it to 'make code clean' project. I am sorry I cannot accept the change like this which touches so many files. It is very easy to introduce potential regression.

**Pull request closed without merging**
