### PR TITLE
code rule

### PR DESCRIPTION
**Pull request by wangnimaa**
## What is the purpose of the change

code rule

We need uniform coding rules.It's too casual now.

### CODE REVIEW

**Comment by wangnimaa** [comment]
> ## What is the purpose of the change
> code rule
> 
> ## Brief changelog
> XXXXX
> 
> ## Verifying this change
> XXXXX
> 
> Follow this checklist to help us incorporate your contribution quickly and easily:
> 
> * [x]  Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
> * [ ]  Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
> * [ ]  Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
> * [ ]  Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
> * [ ]  Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
> * [ ]  If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).



> ## What is the purpose of the change
> XXXXX
> 
> ## Brief changelog
> XXXXX
> 
> ## Verifying this change
> XXXXX
> 
> Follow this checklist to help us incorporate your contribution quickly and easily:
> 
> * [x]  Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
> * [ ]  Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
> * [ ]  Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
> * [ ]  Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
> * [ ]  Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
> * [ ]  If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

**Comment by CrazyHZM** [comment]
please resolve conflicts.

**Comment by wangnimaa** [comment]
> please resolve conflicts.

Ok, I get it now, thanks！

**Comment by htynkn** [comment]
I agree with uniform coding rules. But I personally more prefer use tool to make sure  necessary code rule is applied to project.

I think we need discuss what rule we need apply, for example, I see some Override was added. If we agree to must have Override annotation, we should add a checkstyle rule (if rule existed)
Another example is allow single-line statements without braces or not, it also something need discuss

**Comment by wangnimaa** [comment]
> I agree with uniform coding rules. But I personally more prefer use tool to make sure necessary code rule is applied to project.
> 
> I think we need discuss what rule we need apply, for example, I see some Override was added. If we agree to must have Override annotation, we should add a checkstyle rule (if rule existed)
> Another example is allow single-line statements without braces or not, it also something need discuss

last year ,I propose this issue ,https://github.com/apache/incubator-dubbo/issues/2553.we discuss about the issues .I've been solving these problems.

**Comment by htynkn** [comment]
> > I agree with uniform coding rules. But I personally more prefer use tool to make sure necessary code rule is applied to project.
> > I think we need discuss what rule we need apply, for example, I see some Override was added. If we agree to must have Override annotation, we should add a checkstyle rule (if rule existed)
> > Another example is allow single-line statements without braces or not, it also something need discuss
> 
> last year ,I propose this issue ,https://github.com/apache/incubator-dubbo/issues/2553.we discuss about the issues .I've been solving these problems.


Sure. I see 
@ralf0131 would you mind have a look? This is related to https://github.com/apache/incubator-dubbo/issues/2553

**Comment by ralf0131** [comment]
@htynkn I agree with adding more code rules. Shall we enhance https://github.com/apache/incubator-dubbo/tree/master/codestyle ?

**Comment by ralf0131** [comment]
> Ideally we should add code checkstyle rule to check it automatically instead of fix them one by one manually. considering this PR is related a previous issue and already has some discuss, I'm ok to accept it. If there is no other comment for this PR. I will do merge later

+1

**Pull request merged**
