### PR TITLE
[Dubbo-master] Fix fail when loop reference test on protostuff

### PR DESCRIPTION
**Pull request by Bricks-Man**
## What is the purpose of the change

Loop reference test pass on protostuff

## Brief changelog
Change ProtobufIOUtil to GraphIOUtil
see https://github.com/protostuff/protostuff/issues/258

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by khanimteyaz** [comment]
@Bricks-Man  thanks for the PR. could plz add UT for the same, so that we could have someone to catch if we miss in future.

**Comment by Bricks-Man** [comment]
> Hi, would you please add a unit test for this pull request?
Hi,My unit test is ProtostuffSerializationTest.class，It‘s worked.Before my change,there is a override method named test_LoopReference,it's a empty method.

**Comment by biyuhao** [comment]
Hi @ralf0131 
`ProtostuffSerializationTest` is extended from `AbstractSerializationTest`
I think simply remove this `Override` method makes `AbstractSerializationTest#test_LoopReference` effective.

BTW, @Bricks-Man would you mind to remove unused import (`import org.junit.jupiter.api.Test;`) in `ProtostuffSerializationTest ` please.

**Comment by biyuhao** [comment]
Hi @ralf0131 
`ProtostuffSerializationTest` is extended from `AbstractSerializationTest`
I think simply remove the `Override` method makes `AbstractSerializationTest#test_LoopReference()` effective which will cover this situation.

BTW, @Bricks-Man would you mind to remove unused import (`import org.junit.jupiter.api.Test;`) in `ProtostuffSerializationTest`?

**Pull request merged**
