### PR TITLE
circuitBreaker

### PR DESCRIPTION
**Pull request by wanhuhou**
## What is the purpose of the change
Add CircuitBreaker

### CODE REVIEW

**Comment by ralf0131** [comment]
1. The CI has failed. 
2. This is a significant change,  you need to sign the SGA before merging.

**Comment by jvz** [comment]
Hello,

Your software grant has been filed. Thanks!

**Comment by chickenlj** [comment]
Hello wanhuhou,

Thanks for your contribution, instead of a circuitbreaker i think your implementation is more like a new policy of LoadBalance. 

And after having a discussion with the dubbo team, i think below is the enhancements we should do:
* A foundamental Metrics module.
* Add a new LoadBalance Policy which can detect node healthy.
* Add a new Cluster Policy which can short-circuit and switch to fallback automically. More like a embedded circuitbreaker.
* Provide a demo of integrating Hystrix with Dubbo.

**Comment by chickenlj** [comment]
#1924 #1923 #1922

**Pull request closed without merging**
