### PR TITLE
fix referenceBean initialization issue

### PR DESCRIPTION
**Pull request by YoungHu**
## What is the purpose of the change

merge pull request #1999 into 2.6.x branch 

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [x] Run `mvn clean install -DskipTests` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by beiwei30** [comment]
thanks :)

**Comment by qixiaobo** [comment]
We meet this problem again. I will upgrade version to fix  this problem

**Comment by qixiaobo** [comment]
Too hard to find which version solves this problem.
No changeLog  about this.
Maybe I should try the newest 2.6.x version
image
image

Maybe 2.6.5 or 2.6.6

**Comment by qixiaobo** [comment]
image
2.6.5 not work

**Comment by qixiaobo** [comment]
image
I have to use 2.6.6 version

**Pull request merged**
