### PR TITLE
upgrade libthrift version and add nature thrift support option 

### PR DESCRIPTION
**Pull request by lovepoem**
## What is the purpose of the change
1.upgrade `libthrift` to version`0.11.0`
2.add nature thrift support option 
3.upgrade `fastjson` to version `1.2.46`
## Brief changelog
Code in module dubbo/dubbo-rpc/dubbo-rpc-thrift  is modified
## Verifying this change
1.Config in `dubbo/dubbo-rpc/dubbo-rpc-thrift/src/test/resources/dubbo-demo-consumer.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://code.alibabatech.com/schema/dubbo"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
    http://code.alibabatech.com/schema/dubbo http://code.alibabatech.com/schema/dubbo/dubbo.xsd">

    <dubbo:application name="dubbo-demo-consumer"/>

    <dubbo:registry address="zookeeper://127.0.0.1:2181"/>

    <dubbo:protocol name="thrift"/>

    <dubbo:reference id="demoService" nativethrift="true" interface="com.alibaba.dubbo.rpc.gen.thrift.Demo$Iface" timeout="1000000"/>

</beans>
```

add `nativethrift="true"` property

2.Run main method of  `dubbo/dubbo-rpc/dubbo-rpc-thrift/src/test/java/com/alibaba/dubbo/rpc/examples/DubboThriftDemoConsumer.java tp startup the provider service`

### CODE REVIEW

**Comment by chickenlj** [comment]
Excellent, i will have a review on it.

**Comment by ralf0131** [comment]
1. Please fix the CI failure
2. Please resolve the conflicts.

**Comment by diecui1202** [comment]
I think we could implement a protocol extension named "native-thrift", and place it under http://github.com/dubbo

**Comment by wuhuajie** [comment]
Wonder to know which version this issue is included in?

**Comment by lovepoem** [comment]
Now the thrift issues can be in the new project  : https://github.com/dubbo/dubbo-rpc-native-thrift  @wuhuajie

**Pull request closed without merging**
