### PR TITLE
add the notice of checkstyle

### PR DESCRIPTION
**Pull request by lexburner**
## What is the purpose of the change

code check style needs more details to avoid to confuse the contributor.

## Brief changelog

CONTRIBUTING.md

### CODE REVIEW

**Comment by lovepoem** [comment]
Looks like dubbo/CONTRIBUTING.md and http://dubbo.apache.org/en-us/docs/developers/guide_dev.html are duplicates. Can we just maintain one?

**Comment by lovepoem** [comment]
dubbo/FAQ.md  and http://dubbo.apache.org/en-us/docs/developers/user-guide/faq_dev.html  are also duplicates

**Comment by lovepoem** [comment]
Look good to me

**Comment by lexburner** [comment]
We should maintain two places, the master trunk must own the Contributing.md, i will copy this change to the dubbo blog later.

**Pull request merged**
