### PR TITLE
add jdk11 to travis ci

### PR DESCRIPTION
**Pull request by lovepoem**
## What is the purpose of the change

add jdk11 to travis ci
java11 is coming: http://openjdk.java.net/projects/jdk/11/

## Brief changelog

.travis.yml

## Verifying this change

ci success

### CODE REVIEW

**Comment by htynkn** [comment]
please refer to this https://github.com/jacoco/jacoco/issues/663
Jacoco need to upgrade to 0.8.2 first to support jdk11

**Comment by lovepoem** [comment]
@htynkn ，thanks for your help, it is success now

**Comment by htynkn** [comment]
@lovepoem there are two things we need discuss before merge this pr:
+ jdk11 will official release at end of this month, do we start official support  now? or add `allow fail` to jdk11 (refer to https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail)
+ we have jdk8~jdk11 in travis ci configuartion, I suggest to have a discuss in mail list to confirm which jdk version we official support.

**Comment by diecui1202** [comment]
Looks good to me.

**Pull request merged**
