### PR TITLE
rename ClassHelper to ClassUtils, add MethodUtils

### PR DESCRIPTION
**Pull request by LiZhenNet**
## What is the purpose of the change

rename ClassHelper to ClassUtils

## Brief changelog
1. add ClassUtils to replace ClassHelper , ClassHelper add deprecated annotation.
2. add MethodUtils,  move isSetter/isGetter into it.

Next step : 
Merging 
org.apache.dubbo.common.compiler.support.ClassUtils,
org.apache.dubbo.config.spring.util.ClassUtils,
org.apache.dubbo.metadata.definition.util.ClassUtils,

## Verifying this change
UT

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by LiZhenNet** [comment]
> I have some questions:
> 
> 1. Why do we need such a change?
> 2. What is the difference between org.apache.dubbo.common.compiler.support.ClassUtils and org.apache.dubbo.common.utils.ClassUtils?

1. I think ClassHelper is not standard in Dubbo, and It has some methods on Method.class.
2.Some of these two classes are the same, Are we considering merging them?

**Comment by ralf0131** [comment]
> 1. I think ClassHelper is not standard in Dubbo, and It has some methods on Method.class.
> 2. Some of these two classes are the same, Are we considering merging them?

If they are duplicated, I think it is better to merge them. How do you think? Are you planning to do it next, or in this pull request?

**Comment by ralf0131** [comment]
All the UT are failing, could you please check about that?

**Comment by LiZhenNet** [comment]
> All the UT are failing, could you please check about that?

Sorry for late ,I have fixed it .

**Comment by LiZhenNet** [comment]
@ralf0131 
Is there any progress？

**Pull request merged**
