### PR TITLE
compatible:compatible with dubbox

### PR DESCRIPTION
**Pull request by qinliujie**
## What is the purpose of the change

compatible with dubbox,because dubbox had change dubbo protocol, we compatible with dubbox,so dubbox user can update their dubbo version

## Brief changelog

judge dubbo version to decide whether is dubbox or not

### CODE REVIEW

**Comment by beiwei30** [comment]
should we really need to consider the compatibility to dubbox? is it possible to provide this ability with dubbo's extension mechanism, instead of invading into the core?

**Comment by chickenlj** [comment]
@beiwei30 The original dubbox has changed the core dubbo RPC protocol, so it's impossible now to achieve compatibility with dubbox with extension. 
For users using dubbox to transfer smoothly to dubbo, I think we can create a separate branch and a separate release, for example `2.5.x-dubbox-compatible`. This way, the compatible code would not merged into master branch, it will only exists as a transitional code.

**Comment by kimmking** [comment]
you can use this one:
https://github.com/kimmking/dubbo

1. compatible with dubbox
2. updating newer dependencies
3. integrating with swagger ui

**Comment by zonghaishang** [comment]
@kimmking 
https://github.com/kimmking/dubbo， website is inaccessible.

---------------------
@chickenlj
I think the dubbox code merged into the dubbo trunk was a bad decision. For partial changes to the dubbox protocol, we want to find out whether the repair bug is a private extension.

**Comment by ralf0131** [comment]
1. should be merged into master branch.
2. Since dubbox has been merged into dubbo, is this still something we need to consider?

**Pull request closed without merging**
