### PR TITLE
Better License

### PR DESCRIPTION
**Pull request by carryxyh**
sth to supplement apache 2.0 license

### CODE REVIEW

**Comment by chickenlj** [comment]
Hi @carryxyh ,
Would you please replace the apache header with the netty one?
https://github.com/apache/incubator-dubbo/pull/1865/files#diff-771d58b7b783f77d80a3e99eaa16f998R10

And also, Dubbo currently put all sub-module license in LICENSE, i think there's no need to add an extra `LICENSE.netty.txt` file, put it in LICENSE directly.
https://github.com/apache/incubator-dubbo/blob/master/LICENSE#L266

**Comment by chickenlj** [comment]
Which files should add netty license? I can tell is:
* InternalThreadLocal
* InternalThreadLocalMap

**Comment by carryxyh** [comment]
Oh, I will submit a new pr as soon as possible
Thx

**Comment by chickenlj** [comment]
Resolved with #1866, close this one.

**Pull request closed without merging**
