### PR TITLE
[DUBBO-3537]: dubbox升级dubbo版本的兼容性问题

### LINKED ISSUE #3537: dubbox升级dubbo版本的兼容性问题
我当前系统全部用的是dubbox-2.8.4，部分工程升级到dubbo-2.7之后，新版本客户端调用旧版服务端可以正常调用，旧版客户端调用新版服务报错，报错内容：
`Caused by: com.alibaba.dubbo.remoting.RemotingException: java.io.IOException: Unknown result flag, expect '0' '1' '2', get 4`

### PR DESCRIPTION
**Pull request by beiwei30**
## What is the purpose of the change

fix #3537 

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/incubator-dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by satansk** [comment]
合入该 PR 后，Dubbox 和 Dubbo 就可以兼容了吗？ @beiwei30

**Comment by chickenlj** [comment]
@satansk 要做到和dubbox兼容，恐怕还有一个地方需要做，dubbox直接修改了原生rpc协议编码
https://github.com/dangdangdotcom/dubbox/blob/master/dubbo-rpc/dubbo-rpc-default/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboCodec.java#L187

**Comment by morisenmen** [comment]
我们使用的方案，可供大家参考实现，自定义SPI扩展Codec2，DubboCountCodec，DubboCodec
这两个类，DubboCountCodec引用自定义的DubboCodec，重写encodeResponseData方法，attach判断处理兼容dubbox，本身这个attach判断就是一件兼容处理了dubbox，但是dubbox实现的bug，版本号应该为2.0.0的，invoker的URL传递的是2.8.4，因此这个判断不包含。
扩展实现配置的时候配置自己实现类为dubbo的spi扩展即可
即META-INF/dubbo/internale下面配置扩展[com.alibaba.dubbo/ore.apacha.dubbo].remoting.Codec2
中配置dubbo=自己实现类DubboCountCodec全路径类名即可
该方案只对升级版本的provider做处理，老版本的dubbox完全不需要任何处理
本身可以通过配置实现该功能的，但是dubbo中还有一些bug，可以参考Codec设置的bug说明，我也有备注`https://github.com/apache/dubbo/issues/4628`

**Comment by neeuq** [comment]
@morisenmen 如果在META-INF/dubbo/internal下面配置扩展[com.alibaba.dubbo/ore.apacha.dubbo].remoting.Codec2
中配置dubbo=自己实现类DubboCountCodec全路径类名，是通过java.lang.ClassLoader#getResources来保证自己实现的类优先加载吗？

**Pull request merged**
