### PR TITLE
redis注册中心的监控修改

### PR DESCRIPTION
**Pull request by greatqn**
## What is the purpose of the change

用redis做注册中心时。createMonitor 会报错：

Unsupported redis cluster: failsafe. The redis cluster only supported failover or replicate.

来自RedisRegistry的111行。

## Brief changelog

用redis做注册中心时。createMonitor的failsafe异常修复。

### CODE REVIEW

**Comment by greatqn** [comment]
jedis的修改部分可以略过。太早之前改的。

主要就DubboMonitorFactroy.java里的一句：
        //Constants.CLUSTER_KEY, "failsafe",
        url = url.addParameters( Constants.CHECK_KEY, String.valueOf(false), 

不知为何这里要加这个默认值。
而在RedisRegistry里做了如下校验：
        String cluster = url.getParameter("cluster", "failover");
        if (! "failover".equals(cluster) && ! "replicate".equals(cluster)) {

**Comment by kimmking** [comment]
hi, you should resolve these conflicts first.

**Comment by ralf0131** [comment]
Hi, there is too much conflict to review your changes. Please follow this [guide](https://github.com/apache/incubator-dubbo/blob/master/CONTRIBUTING.md#contribution-flow) to sync your branch with master.

**Comment by diecui1202** [comment]
@greatqn Are you there? Why this PR make so many files changed? Make minimum changes so that others can easy to review.

**Comment by diecui1202** [comment]
@greatqn pls file a new PR. I think this pr needs to be closed firstly.

**Pull request closed without merging**
