### PR TITLE
Reference retries default value

### PR DESCRIPTION
**Pull request by tswstarplanet**
## What is the purpose of the change

Correct the default value of Reference annotation. #2162

### CODE REVIEW

**Comment by diecui1202** [comment]
@tswstarplanet Why this PR has so many commits, but just change 2 java source files?

**Comment by tswstarplanet** [comment]
@diecui1202 I don't kown. It seems to contains all of the submits since I began to submit PR. But the previous PRs have been merged. Does I make some mistakes about the use of github ?

**Comment by diecui1202** [comment]
@tswstarplanet I suggest you checkout a new branch from master, and send a new PR.

How do you think?

**Comment by tswstarplanet** [comment]
@diecui1202 This branch I request to merge was created from my master branch. I do not kown why it is like that. Do I need to delete my repository and fork the official repository once again ?

**Comment by diecui1202** [comment]
@tswstarplanet Maybe your local master branch is out of date. Each branch must be created from the newest master, it's the apache/incubator-dubbo 's master, not your fork repo.

**Comment by diecui1202** [comment]
```
➜  incubator-dubbo git:(master) git remote -v
mine	git@github.com:diecui1202/dubbo.git (fetch)
mine	git@github.com:diecui1202/dubbo.git (push)
origin	git@github.com:apache/incubator-dubbo.git (fetch)
origin	git@github.com:apache/incubator-dubbo.git (push)
```

As the above showing, I checkout to master branch,  which is belongs to apache/incubator-dubbo.git, I will run `git pull` before creating new branches.

After committing on the new branch, I will push it to my own repo. Then create PR.

**Comment by tswstarplanet** [comment]
@diecui1202 If I create a branch from the apache/incubator-dubbo, can I commit code to my own fork and request to merge code ?

**Pull request closed without merging**
