### PR TITLE
Dubbo-3473 Fix Not Properly Closed Resources

### PR DESCRIPTION
**Pull request by kamaci**
## What is the purpose of the change

Connections, streams, files, and other classes that implement the Closeable interface or its super-interface, AutoCloseable, needs to be closed after use.

## Brief changelog

Resources are closed properly.

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by chickenlj** [comment]
Pls. resolve the failed UTs first.

**Comment by kamaci** [comment]
> Pls. resolve the failed UTs first.

I've rollbacked RedisProtocol.java change as fix. It shouldn't auto close resource since it's been handled by destroy().

**Comment by kezhenxu94** [comment]
@kamaci the **DUBBO-XXX** in the title means that this PR is associated with an issue with number **XXX**, in this case it's 3473, so the title should be [DUBBO-3473] ...

**Comment by kamaci** [comment]
> @kamaci the **DUBBO-XXX** in the title means that this PR is associated with an issue with number **XXX**, in this case it's 3473, so the title should be [DUBBO-3473] ...

I've just fixed it 👍

**Pull request merged**
