### PR TITLE
fix isShutdown always return true

### PR DESCRIPTION
**Pull request by ma-xiao-guang-64**
change isShutdown to isTerminated

### CODE REVIEW

**Comment by lovepoem** [comment]
Please synchronize the origin/master branch to resolve the problem of CI check failure

**Comment by ma-xiao-guang-64** [comment]
@lovepoem ok, please review it.

**Comment by cvictory** [comment]
Review the commit , change isShutdown to isTerminated. 

* java.util.concurrent.ExecutorService#isShutdown will return true , after invoking shutdown or shutdownNow.
* java.util.concurrent.ExecutorService#isTerminated will return true, after all tasks have completed execution.

It is correct about this modification.

**Comment by ma-xiao-guang-64** [comment]
@cvictory 
No, isShutdown() will always return true when you invoke shutdown() or shutdownNow().
please confirm this, thank you

**Comment by ralf0131** [comment]
I don't understand what is the purpose of this pull request. What problem have encountered? Can you file an issue to describe it?

**Comment by ma-xiao-guang-64** [comment]
@ralf0131 
我用中文表述一下
当调用-ExecutorService的shutdown方法之后无论ExecutorService是否关闭再次调用shutdown都会返回true。
有段代码`if (!isShutdown(es)) {
newThreadToCloseExecutor(es);
}`其条件永远都返回false，也就是说下面的关闭线程并不会启动

**Comment by ralf0131** [comment]
Hello, thanks for the clarification, I've figured out what you mean.

I think you are correct. 

However,  I argue that it cannot solve the problem completely. `ShutdownNow` uses `Thread.interrupt` to try to interrupt the running threads, if a thread does not respond to the interrupt signal, it will never stop even if you call the shutdownNow for multiple times.

**Comment by ralf0131** [comment]
Anyway, I will merge this pull request. Thanks for the pull request!

**Comment by ma-xiao-guang-64** [comment]
@ralf0131    Thank, if a thread does not respond to the interrupt signal, newThreadToCloseExecutor will work to wait thread finished.

**Pull request merged**
