### PR TITLE
replace the method httpclient which is annotated with “@Deprecated”

### PR DESCRIPTION
**Pull request by GuldanChen**

### CODE REVIEW

**Comment by ralf0131** [comment]
@GuldanChen Can you solve the conflict?

**Comment by kimmking** [comment]
I dont think it's a proper improvement for original codes.
Original codes hold a single httpclient instance and then reuse.
This PR codes make a new httpclient obejct for once invoking.

@GuldanChen you can build a httpclient by builder to adapt original codes.

**Comment by GuldanChen** [comment]
@kimmking @ralf0131  Thank you for your reminding

**Comment by GuldanChen** [comment]
@kimmking that's ok?

**Comment by ralf0131** [comment]
Hi, the CI is still failing, please take a look.

**Comment by diecui1202** [comment]
I've checked the ci result, it's failed because of the unstable case. I've merge master to this branch.

**Comment by diecui1202** [comment]
@kimmking please check this PR again.

**Pull request merged**
