### PR TITLE
revise the naming conventions of test case

### PR DESCRIPTION
**Pull request by kuaike**
## What is the purpose of the change

naming conventions

## Brief changelog

Same as the test case related field of memcached, recommend to fix

## Verifying this change

test case pass

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by satansk** [comment]
Hi @kuaike , thank for your contribution, could you please change the title to English?

**Comment by kezhenxu94** [comment]
> Hi @kuaike , thank for your contribution, could you please change the title to English?

There are also some whitespace changes

**Comment by kuaike** [comment]
> > Hi @kuaike , thank for your contribution, could you please change the title to English?
> 
> There are also some whitespace changes

ok, changed the title.
The some whitespace maybe cause by my Idea config, I will check it. 
Thanks for telling me.

**Comment by kuaike** [comment]
Find the reasons of whitespaces caused. Need to change Git default config. Test passed.
`git config --global core.autocrlf false`
[solution](https://github.com/apache/incubator-dubbo/pull/3427#issuecomment-460051834)

@kezhenxu94 It will not happen again.

**Comment by satansk** [comment]
> > Hi @kuaike , thank for your contribution, could you please change the title to English?
> 
> There are also some whitespace changes

Yes, @kuaike could you please correct it, or you can submit another PR :)

**Comment by kuaike** [comment]
> > > Hi @kuaike , thank for your contribution, could you please change the title to English?
> > 
> > 
> > There are also some whitespace changes
> 
> Yes, @kuaike could you please correct it, or you can submit another PR :)

Done. @satansk

**Comment by kuaike** [comment]
The Travis CI build failed, maybe because of time out ...  
Increase the timeout config, maybe fix it.

image
image

**Comment by kezhenxu94** [comment]
@kuaike I think you could push an empty commit to re-trigger the CI build or contact one of the admins to re-trigger manually

**Comment by kuaike** [comment]
https://github.com/apache/incubator-dubbo/pull/3506#issuecomment-465459824
@carryxyh Could you help me do re-trigger manually? Maybe change the config of re-trigger at the same time.

**Comment by satansk** [comment]
triggered

**Comment by kuaike** [comment]
> Thank you for your contribution! @kuaike

 :) I like it

**Pull request merged**
