### PR TITLE
Optimize ut for serialization model.

### PR DESCRIPTION
**Pull request by carryxyh**
1. Integrate the unit test of the serialization module, code reuse.
2. Remove redundant unit tests and pojo classes.
3. Remove the useless pojo class in the common module.

related issue:
https://github.com/apache/incubator-dubbo/issues/2623

### CODE REVIEW

**Comment by carryxyh** [comment]
> I'm happy to have a issue to investigate configuration issue for coverage stuff.

I agree.

**Comment by carryxyh** [comment]
@lovepoem @htynkn 
I will send an email to ask other people in the community. 
Maybe someone else has had a similar experience?

**Comment by carryxyh** [comment]
@htynkn @lovepoem 
The unit test coverage of the response is now accurate, please check again.

**Comment by diecui1202** [comment]
It's LGTM.

**Comment by lovepoem** [comment]
Look Good To Me

**Pull request merged**
