### PR TITLE
Add serializationConstant

### PR DESCRIPTION
**Pull request by CrazyHZM**
## What is the purpose of the change
Constants is too large, divided into module Constants to manage constants
follow  #3967
add  SerializationConstants

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by beiwei30** [comment]
it is indeed a good idea, but it is incomplete solution. Instead, we should examine Constants throughly and classify all constants in it carefully. What I suggest is we should divide this work into four steps:

1.  Examine Constants.java and classify throughly.
2. Introduce new sub package 'constants' as what you did, and introduce new Constants classes in it.
3. Start to switch from old Constants to new Constants
4. Remove the old Constants.

I will file one new issue to track this work.

**Comment by beiwei30** [comment]
It's tracked now by https://github.com/apache/incubator-dubbo/issues/3137. I will do the step 1 first, after that, we could start to divide the works for step2 and step3

**Comment by CrazyHZM** [comment]
> 它现在由[＃3137](https://github.com/apache/incubator-dubbo/issues/3137)跟踪。我将首先执行第1步，之后，我们可以开始分割第2步和第3步的工作

This is a good plan. After your first step is completed, I will participate in the follow-up work.

**Comment by beiwei30** [comment]
sure, thanks.

**Pull request closed without merging**
