### PR TITLE
[dubbo-2029]: upgrade netty4 to the latest release and make it the default option for transporter 

### PR DESCRIPTION
**Pull request by beiwei30**
…lt option for transporter

## What is the purpose of the change

issue#2029: upgrade netty4 to the latest release and make it the default option for transporter 

## Brief changelog

dependencies-bom/pom.xml
dubbo-common/src/main/java/org/apache/dubbo/common/Constants.java
dubbo-config/dubbo-config-api/pom.xml
dubbo-config/dubbo-config-spring/pom.xml
dubbo-demo/dubbo-demo-consumer/pom.xml
dubbo-demo/dubbo-demo-provider/pom.xml
dubbo-monitor/dubbo-monitor-default/pom.xml
dubbo-registry/dubbo-registry-default/pom.xml
dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/Transporter.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/exchange/support/header/HeartbeatHandlerTest.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/ClientReconnectTest.java
dubbo-remoting/dubbo-remoting-netty/src/test/java/org/apache/dubbo/remoting/transport/netty/NettyClientTest.java
dubbo-remoting/dubbo-remoting-netty4/src/main/java/org/apache/dubbo/remoting/transport/netty4/NettyClientHandler.java
dubbo-remoting/dubbo-remoting-p2p/pom.xml
dubbo-rpc/dubbo-rpc-dubbo/pom.xml
dubbo-rpc/dubbo-rpc-thrift/pom.xml

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by chickenlj** [comment]
Agree to change the default transporter to netty4. 

Only one thing to note: this change is not transparent to the user, they should guarantee netty4 in the classpath, which is not always satisfied since their projects may rely on netty3 by default. But I think it's ok, a release note for incompatible upgrade is enough.

**Comment by chickenlj** [comment]
To continue use `netty`, how about this way:

based on your PR, add the following items,
For [netty4/Transporter](https://github.com/apache/incubator-dubbo/blob/master/dubbo-remoting/dubbo-remoting-netty4/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.Transporter)
```properties
netty=org.apache.dubbo.remoting.transport.netty4.NettyTransporter
netty4=org.apache.dubbo.remoting.transport.netty4.NettyTransporter
```

And 

For [netty3/Transporter](https://github.com/apache/incubator-dubbo/blob/master/dubbo-remoting/dubbo-remoting-netty/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.Transporter)
```properties
netty=org.apache.dubbo.remoting.transport.netty4.NettyTransporter
netty4=org.apache.dubbo.remoting.transport.netty4.NettyTransporter
```

**Comment by chickenlj** [comment]
Keep `netty` no changed
```java
@SPI("netty")
 public interface Transporter {
```

**Comment by zonghaishang** [comment]
Perhaps the `server` should be removed and passed to the client.

**Comment by chickenlj** [comment]
@zonghaishang Agree to remove `server` from the client, and this can be achieved within this issue #2030

**Pull request merged**
