### PR TITLE
[Dubbo-889-Attachments] support implicit delivery of attachments from provider to consumer

### LINKED ISSUE #889: dubbo provider怎么传递消息给consumer
有个特殊的需求，需要让provider传递值给consumer，类似consumer能传递attachment给provider一样。

阅读源码发现，provider好像只能传递返回值或者异常给consumer。

请问有什么办法可以办到这一点吗？

Dubbo version: 2.5.3.1

### PR DESCRIPTION
**Pull request by chickenlj**
## What is the purpose of the change

Fixes #889, support implicit delivery of attachments from provider to consumer

## Brief changelog

Not completely finished yet.

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/alibaba/dubbo/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by axibx** [comment]
我认为这个commit存在bug,
encodeResponseData方法在执行结果编码时，不应该依赖provide的version,
我觉得应该根据client请求的version，决定是否需要返回Attachments，否则会存在兼容性问题。

**Comment by Authorlove** [comment]
thumbs up

**Comment by chickenlj** [comment]
Response res = new Response(req.getId(), req.getVersion());
Thanks for your report.

Actually, the version of response comes from request, it’s a little confusing. At first, i use `attributes in RpcContext` to pass version of request, but now i think it’s ok to keep the response version synced with that of request.

What  do you think?

**Comment by axibx** [comment]
好吧，可能是我看错了？看成如下代码了：
boolean attach = Version.isSupportResponseAttatchment(DUBBO_VERSION);
我重新确认下，现在不存在这个问题。谢谢

**Comment by nzomkxia** [comment]
can you commit a test case for the change?

**Comment by chickenlj** [comment]
I will resolve the conflicts, add some test cases.

**Comment by chickenlj** [comment]
Sorry, some problem with the personal remote repository, i will submit a new PR.

**Pull request closed without merging**
