### PR TITLE
New ascii logo.

### PR DESCRIPTION
**Pull request by carryxyh**
New ascii logo.

Voting is here:
https://github.com/apache/incubator-dubbo/issues/2332

### CODE REVIEW

**Comment by carryxyh** [comment]
The effect of the new LOGO is：
image

**Comment by diecui1202** [comment]
looks good to me.

**Comment by diecui1202** [comment]
@carryxyh 2.6.x will also get this change?

**Comment by diecui1202** [comment]
Got it.

**Pull request merged**
