### PR TITLE
fix annotion @DubboComponetScan doesn't work in spring3

### PR DESCRIPTION
**Pull request by HelloFy**
## What is the purpose of the change

fix the @DubboComponentScan doesn't work in spring 3.2.18.RELEASE

## Brief changelog

modify postProcessBeanFactory() eto ensure the scan annotion of Service or Refrence

### CODE REVIEW

**Comment by chickenlj** [comment]
I think there's too many unrelated changes, can you please recreate a PR that will contains only necessary changes?

**Comment by ralf0131** [comment]
Yes, I agree with @chickenlj. Unnecessary changes will make the reviewer confused. Please keep only the minimal changes.

**Comment by kimmking** [comment]
Agree with @chickenlj too.
Unnecessary Formatting codes.

**Comment by HelloFy** [comment]
can you review this pr?

**Comment by chickenlj** [comment]
@HelloFy Sorry for late reply, mercy will review it soon.

**Comment by mercyblitz** [comment]
@HelloFy The change of  [ServiceAnnotationBeanPostProcessor.java](https://codecov.io/gh/alibaba/dubbo/pull/1318/diff?src=pr&el=tree#diff-ZHViYm8tY29uZmlnL2R1YmJvLWNvbmZpZy1zcHJpbmcvc3JjL21haW4vamF2YS9jb20vYWxpYmFiYS9kdWJiby9jb25maWcvc3ByaW5nL2JlYW5zL2ZhY3RvcnkvYW5ub3RhdGlvbi9TZXJ2aWNlQW5ub3RhdGlvbkJlYW5Qb3N0UHJvY2Vzc29yLmphdmE=) seems valueless , The Spring Framework will handle duplicated  `@Component` definitions, please refer code `org.springframework.context.annotation.ClassPathBeanDefinitionScanner#checkCandidate` ( From Spring Framework `3.2.14.RELEASE` ：
```java
	protected boolean checkCandidate(String beanName, BeanDefinition beanDefinition) throws IllegalStateException {
		if (!this.registry.containsBeanDefinition(beanName)) {
			return true;
		}
		BeanDefinition existingDef = this.registry.getBeanDefinition(beanName);
		BeanDefinition originatingDef = existingDef.getOriginatingBeanDefinition();
		if (originatingDef != null) {
			existingDef = originatingDef;
		}
		if (isCompatible(beanDefinition, existingDef)) {
			return false;
		}
		throw new ConflictingBeanDefinitionException("Annotation-specified bean name '" + beanName +
				"' for bean class [" + beanDefinition.getBeanClassName() + "] conflicts with existing, " +
				"non-compatible bean definition of same name and class [" + existingDef.getBeanClassName() + "]");
	}
```

**Comment by beiwei30** [comment]
current spring support doesn't work with spring 3 indeed:

```shell
Exception in thread "main" org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: com.alibaba.dubbo.config.spring.context.annotation.DubboConfigConfiguration$Single was @Import'ed but is not annotated with @Configuration nor does it declare any @Bean methods; it does not implement ImportSelector or extend ImportBeanDefinitionRegistrar. Update the class to meet one of these requirements or do not attempt to @Import it.
Offending resource: class path resource [com/alibaba/dubbo/config/spring/context/annotation/DubboConfigConfiguration$Single.class]
	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:68)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.registerBeanDefinitionForImportedConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:121)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:111)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:317)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:225)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:639)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:464)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:73)
	at com.alibaba.dubbo.samples.annotation.AnnotationProvider.main(AnnotationProvider.java:37)
```

**Comment by mercyblitz** [comment]
@beiwei30 `ImportBeanDefinitionRegistrar` was introduced since Spring Framework 3.1, and 3.2.x was in EOL, thus it's unreasonable that current Dubbo was compatible with Spring 3.0.

**Comment by mercyblitz** [comment]
In summary, I will close this PR.

**Comment by beiwei30** [comment]
@mercyblitz I think it's reasonable to support spring 4.x above only, but would you mind to update user doc to indicate this?

* Chinese: http://dubbo.apache.org/books/dubbo-user-book/configuration/annotation.html
* English: http://dubbo.apache.org/books/dubbo-user-book-en/configuration/annotation.html

**Comment by mercyblitz** [comment]
@beiwei30 Ok

**Pull request closed without merging**
